"""
app.py — FIFA World Cup 2026 AI Prediction System
Home page. Navigate using the sidebar links (auto-generated by Streamlit MPA).
"""

import streamlit as st
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

st.set_page_config(
    page_title="WC 2026 AI Predictor",
    page_icon="⚽",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── GLOBAL DARK THEME CSS ──────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;600;700&family=Inter:wght@300;400;500;600&display=swap');

html, body, [class*="css"] { font-family:'Inter',sans-serif; background-color:#0d0d1a !important; color:#e0e0e0; }

section[data-testid="stSidebar"] {
    background:linear-gradient(180deg,#0a0a1a 0%,#0d0d24 100%) !important;
    border-right:1px solid #1e1e3a;
}
section[data-testid="stSidebar"] * { color:#ccc !important; }
section[data-testid="stSidebar"] a { color:#f0b429 !important; font-weight:600; }

.main .block-container { background-color:#0d0d1a !important; padding-top:1.5rem; max-width:1400px; }

.stSelectbox > div > div,
.stMultiselect > div > div { background-color:#12122a !important; border:1px solid #2a2a4a !important; color:white !important; }

.stButton > button {
    background:linear-gradient(135deg,#f0b429,#e67e22) !important;
    color:#1a1a1a !important; font-weight:700 !important;
    border:none !important; border-radius:8px !important;
    font-family:'Rajdhani',sans-serif !important; letter-spacing:1px;
}
.stButton > button:hover { opacity:0.9 !important; }

.stTabs [data-baseweb="tab-list"] { background:#12122a; border-radius:10px; gap:4px; }
.stTabs [data-baseweb="tab"] { background:transparent; color:#888 !important; border-radius:8px; font-weight:600; }
.stTabs [aria-selected="true"] { background:linear-gradient(135deg,#f0b429,#e67e22) !important; color:#1a1a1a !important; }

.stDataFrame { border:1px solid #1e1e3a !important; border-radius:10px !important; }
.stDataFrame * { color:#ddd !important; background-color:#0d0d1a !important; }

h1,h2,h3,h4 { font-family:'Rajdhani',sans-serif !important; color:#f0b429 !important; letter-spacing:1px; }

details { background:#12122a !important; border-radius:10px !important; border:1px solid #1e1e3a !important; }

::-webkit-scrollbar { width:6px; }
::-webkit-scrollbar-track { background:#0d0d1a; }
::-webkit-scrollbar-thumb { background:#2a2a4a; border-radius:3px; }
</style>
""", unsafe_allow_html=True)

# ── SIDEBAR LOGO ──────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("""
    <div style='text-align:center;padding:1rem 0 1.5rem 0;'>
        <div style='font-size:3rem;'>⚽</div>
        <div style='font-family:Rajdhani,sans-serif;font-size:1.5rem;font-weight:700;color:#f0b429;'>WC 2026 AI</div>
        <div style='color:#666;font-size:0.75rem;letter-spacing:2px;text-transform:uppercase;'>Prediction System</div>
    </div>
    <hr style='border-color:#1e1e3a;margin:0.5rem 0;'>
    <div style='color:#555;font-size:0.72rem;text-align:center;padding:0.5rem;'>
        XGBoost · 43K+ matches<br>Elo Ratings · FIFA Player Stats
    </div>
    """, unsafe_allow_html=True)

# ── HOME PAGE CONTENT ─────────────────────────────────────────────────────────
st.markdown("""
<div style='text-align:center;padding:2rem 1rem 1rem 1rem;'>
    <div style='font-family:Rajdhani,sans-serif;font-size:3.5rem;font-weight:700;
                background:linear-gradient(135deg,#f0b429,#e67e22);
                -webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;'>
        FIFA WORLD CUP 2026
    </div>
    <div style='font-family:Rajdhani,sans-serif;font-size:1.8rem;color:#ccc;font-weight:400;'>
        AI Prediction &amp; Analytics System
    </div>
    <div style='color:#888;max-width:600px;margin:1rem auto;font-size:0.95rem;line-height:1.6;'>
        Machine learning-powered football predictions trained on 43,000+ international matches.
        Use the <b style="color:#f0b429;">sidebar</b> to navigate all pages.
    </div>
</div>
""", unsafe_allow_html=True)

# Feature cards
features = [
    ("🔮", "Match Prediction",      "AI win probabilities, radar charts, and insights for any matchup."),
    ("🏆", "Tournament Simulator",   "Full WC 2026 simulations — group stage, knockouts, Monte Carlo."),
    ("📊", "Team Analytics",         "Elo history, form trends, win rates, and match records."),
    ("👤", "Player Analytics",       "Compare nations by FIFA attribute ratings."),
    ("🤖", "Model Insights",         "ML accuracy, confusion matrices, and feature importance."),
    ("📜", "Historical Data",        "Explore 43,000+ international matches with filters."),
]

c1, c2, c3 = st.columns(3)
for idx, (icon, title, desc) in enumerate(features):
    col = [c1, c2, c3][idx % 3]
    with col:
        st.markdown(f"""
        <div style='background:#12122a;border-radius:14px;padding:1.5rem;margin:0.5rem 0;
                    border:1px solid #1e1e3a;border-top:3px solid #f0b429;'>
            <div style='font-size:2rem;margin-bottom:0.5rem;'>{icon}</div>
            <div style='font-family:Rajdhani,sans-serif;font-size:1.1rem;font-weight:700;
                        color:#f0b429;margin-bottom:0.5rem;'>{title}</div>
            <div style='color:#aaa;font-size:0.88rem;line-height:1.5;'>{desc}</div>
        </div>
        """, unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

# Dataset stats
st.markdown("### 📊 Dataset Overview")
try:
    from utils.data_loader import load_match_features, load_player_aggregates
    df = load_match_features()
    players = load_player_aggregates()
    teams_count = len(set(df["_home_team"]) | set(df["_away_team"]))
    wc_matches = len(df[df["_tournament"].str.contains("World Cup", na=False)])
    player_countries = players["country"].nunique()
except Exception:
    df = None
    teams_count, wc_matches, player_countries = 180, 8827, 188

s1, s2, s3, s4 = st.columns(4)
for col, label, val, color in [
    (s1, "Total Matches",     f"{len(df):,}" if df is not None else "43,364", "#f0b429"),
    (s2, "National Teams",    str(teams_count),                               "#4CAF50"),
    (s3, "World Cup Matches", f"{wc_matches:,}",                              "#3498db"),
    (s4, "Countries w/ Data", str(player_countries),                          "#9b59b6"),
]:
    with col:
        st.markdown(f"""
        <div style='background:#12122a;border-radius:12px;padding:1.2rem;text-align:center;
                    border-bottom:3px solid {color};'>
            <div style='color:{color};font-size:2rem;font-weight:800;font-family:Rajdhani,sans-serif;'>{val}</div>
            <div style='color:#888;font-size:0.8rem;text-transform:uppercase;letter-spacing:1px;'>{label}</div>
        </div>
        """, unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

# WC 2026 Groups preview
st.markdown("### 🗺️ FIFA World Cup 2026 — Groups")
from utils.simulator import WC2026_GROUPS
group_items = list(WC2026_GROUPS.items())
for row_start in range(0, len(group_items), 6):
    gcols = st.columns(6)
    for col, (gname, gteams) in zip(gcols, group_items[row_start:row_start+6]):
        with col:
            teams_str = "<br>".join(f"<span style='color:#ddd;'>{t}</span>" for t in gteams)
            st.markdown(f"""
            <div style='background:#12122a;border-radius:10px;padding:0.8rem;
                        border-top:2px solid #f0b429;text-align:center;font-size:0.82rem;margin:0.3rem 0;'>
                <div style='color:#f0b429;font-weight:700;margin-bottom:0.4rem;'>Group {gname}</div>
                {teams_str}
            </div>
            """, unsafe_allow_html=True)
